version: '2'
services:
    jhipster-mini-book-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipster-mini-book/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipster-mini-book
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
